src/nucoris.webapp/Pages/Admitted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using nucoris.application.queries;
using nucoris.queries.PatientStateView;
using nucoris.webapp.Models;

namespace nucoris.webapp.Pages
{
    public class AdmittedModel : PageModel
    {
        private readonly MediatR.IMediator _mediator;

        public List<PatientVM> AdmittedPatients { get; set; }

        public AdmittedModel(MediatR.IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync()
        {
            // Get all admitted patients:
            var specification = new PatientStateViewSpecification(PatientAdmissionState.Admitted);
            var query = new PatientStateQuery(specification);
            var patients = await _mediator.Send(query);

            this.AdmittedPatients = patients.Select(qp => new PatientVM(qp)).
                OrderBy(vp => vp.DisplayName).ToList();
        }
    }
}

src/nucoris.webapp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace nucoris.webapp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/nucoris.webapp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace nucoris.webapp.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/nucoris.webapp/Pages/MyOrders.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using nucoris.application.interfaces;
using nucoris.application.queries;
using nucoris.queries.ActiveOrdersView;
using nucoris.webapp.Models;

namespace nucoris.webapp.Pages
{
    public class MyOrdersModel : PageModel
    {
        private readonly MediatR.IMediator _mediator;
        private readonly IUnitOfWork _unitOfWork;

        public List<PatientVM> OrdersAssignedToMe { get; set; }

        public MyOrdersModel(MediatR.IMediator mediator, IUnitOfWork unitOfWork)
        {
            _mediator = mediator;
            _unitOfWork = unitOfWork;
        }

        public async Task OnGetAsync()
        {
            var user = _unitOfWork.CurrentUser;

            var specification = ActiveOrdersViewSpecification.ForUser(user.Id);
            var query = new ActiveOrdersQuery(specification);
            var orders = await _mediator.Send(query);

            this.OrdersAssignedToMe = new List<PatientVM>();

            var patientOrders = orders.GroupBy(o => o.QueryOrder.PatientId);

            foreach(var group in patientOrders)
            {
                var patient = new PatientVM(group.First());
                var order = group.First().QueryOrder;

                patient.ActiveAdmission.Orders = group.Select(o => new OrderVM(o)).ToList();

                this.OrdersAssignedToMe.Add(patient);
            }
        }
    }
}

src/nucoris.webapp/Pages/NewAdmission.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using nucoris.application.queries;
using nucoris.queries.PatientStateView;
using nucoris.webapp.Models;

namespace nucoris.webapp.Pages
{
    public class NewAdmissionModel : PageModel
    {
        private readonly MediatR.IMediator _mediator;

        public List<PatientVM> FoundPatients { get; set; }

        [BindProperty]
        public NewPatientVM NewPatient { get; set; }

        public NewAdmissionModel(MediatR.IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IActionResult> OnPostSearchAsync(string mrn)
        {
            if( ! String.IsNullOrWhiteSpace(mrn) )
            {
                // Search by MRN:
                var specification = new PatientStateViewSpecification(mrn);
                var query = new PatientStateQuery(specification);
                var patients = await _mediator.Send(query);

                if( patients.Any())
                {
                    this.FoundPatients = patients.Select(qp => new PatientVM(qp)).ToList();
                }      
                else
                {
                    // Initialize NewPatient to transfer Mrn to form to enter new patient's name and DOB.
                    this.NewPatient = new NewPatientVM() { Mrn = mrn };
                }

                return new PageResult();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAdmitAsync(Guid patientId)
        {
            if (patientId != default(Guid))
            {
                // Create Admit Command:
                var cmd = new application.commands.AdmitPatientCommand(patientId, DateTime.UtcNow);
                var result = await _mediator.Send(cmd);

                if (result.Successful)
                {
                    return RedirectToPage("PatientDetails", new { patientId });
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPostNewPatientAsync()
        {
            if (ModelState.IsValid)
            {
                // Create New Patient and New Admit Commands:
                var patientCmd = new application.commands.CreatePatientCommand(
                    this.NewPatient.Mrn, this.NewPatient.GivenName, this.NewPatient.FamilyName, this.NewPatient.DateOfBirth);
                var patientResult = await _mediator.Send(patientCmd);

                if (patientResult.Successful)
                {
                    var patientId = patientResult.CreatedEntityId;
                    var admissionCmd = new application.commands.AdmitPatientCommand(patientId, DateTime.UtcNow);
                    var result = await _mediator.Send(admissionCmd);

                    if (result.Successful)
                    {
                        return RedirectToPage("PatientDetails", new { patientId });
                    }
                }
            }

            return Page();
        }
    }
}

src/nucoris.webapp/Pages/NewOrder.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using nucoris.application.interfaces;
using nucoris.application.interfaces.ReferenceData;
using nucoris.application.interfaces.repositories;
using nucoris.webapp.Models;

namespace nucoris.webapp.Pages
{
    public class NewOrderModel : PageModel
    {
        private readonly MediatR.IMediator _mediator;
        private readonly IPatientRepository _patientRepository;
        private readonly IReferenceDataRepository<MedicationForm, Guid> _medicationFormRepository;
        private readonly IReferenceDataRepository<AdministrationFrequency, Guid> _medicationFrequencyRepository;
        private readonly IUnitOfWork _unitOfWork;

        public PatientVM Patient { get; private set; }
        public SelectList MedicationForms { get; private set; }
        public SelectList AdministrationFrequencies { get; private set; }

        [BindProperty]
        public NewOrderVM NewOrder { get; set; }

        public NewOrderModel(MediatR.IMediator mediator,
            IPatientRepository patientRepository,
            IReferenceDataRepository<MedicationForm,Guid> medicationFormRepository,
            IReferenceDataRepository<AdministrationFrequency, Guid> medicationFrequencyRepository,
            IUnitOfWork unitOfWork)
        {
            _mediator = mediator;
            _patientRepository = patientRepository;
            _medicationFormRepository = medicationFormRepository;
            _medicationFrequencyRepository = medicationFrequencyRepository;
            _unitOfWork = unitOfWork;
        }

        public async Task OnGetAsync(Guid patientId, Guid admissionId)
        {
            var patient = await _patientRepository.GetAsync(patientId);

            if (patient != null)
            {
                this.Patient = new PatientVM()
                {
                    Id = patient.Id,
                    DisplayName = patient.DisplayName,
                    ActiveAdmission = new AdmissionVM() { Id = admissionId}
                };

                var medforms = await _medicationFormRepository.GetManyAsync(whereConditions: null);
                this.MedicationForms = new SelectList(medforms.OrderBy(i => i.DisplayName),
                    nameof(MedicationForm.Id), nameof(MedicationForm.DisplayName));

                var medfrequencies = await _medicationFrequencyRepository.GetManyAsync(whereConditions: null);
                this.AdministrationFrequencies = new SelectList(medfrequencies.OrderBy(i => i.DisplayName),
                    nameof(AdministrationFrequency.Id), nameof(AdministrationFrequency.DisplayName));

                var now = DateTime.Now; // TODO: use UTC and translate to user's time zone
                var suggestedStartTime = new DateTime(now.Year, now.Month, now.Day, now.Hour, 0, 0) + new TimeSpan(1, 0, 0);

                this.NewOrder = new NewOrderVM()
                {
                    PatientId = patientId,
                    AdmissionId = admissionId,
                    StartTime = suggestedStartTime
                };
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                // Create New Order Command:
                var medform = await _medicationFormRepository.GetAsync(this.NewOrder.MedicationId);
                var medfrequency = await _medicationFrequencyRepository.GetAsync(this.NewOrder.FrequencyId);

                var cmd = new application.commands.PrescribeMedicationCommand(
                    this.NewOrder.PatientId, this.NewOrder.AdmissionId,
                    medform.Medication.Name, medform.Dose.Amount, medform.Dose.Unit.Name, medfrequency.Frequency.Name,
                    this.NewOrder.StartTime, this.NewOrder.StartTime.AddDays(100), // In this prototype we ignore EndTime
                    _unitOfWork.CurrentUser.Id);
                var result = await _mediator.Send(cmd);

                if (result.Successful)
                {
                    return RedirectToPage("PatientDetails", new { this.NewOrder.PatientId });
                }
            }

            return Page();
        }

    }
}

src/nucoris.webapp/Pages/PatientAuditTrail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using nucoris.application.queries;
using nucoris.webapp.Models;


namespace nucoris.webapp.Pages
{
    public class PatientAuditTrailModel : PageModel
    {
        private readonly MediatR.IMediator _mediator;

        public nucoris.queries.PatientAuditTrail.Patient PatientAuditTrail { get; set; }

        public PatientAuditTrailModel(MediatR.IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync(Guid patientId)
        {
            var query = new PatientAuditTrailQuery(patientId);
            this.PatientAuditTrail = await _mediator.Send(query);
        }
    }
}

src/nucoris.webapp/Pages/PatientDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using nucoris.application.interfaces.repositories;
using nucoris.application.queries;
using nucoris.webapp.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace nucoris.webapp.Pages
{
    public class PatientDetailsModel : PageModel
    {
        private readonly MediatR.IMediator _mediator;
        private readonly IOrderRepository _orderRepository;

        public PatientVM Patient { get; set; }

        public PatientDetailsModel(MediatR.IMediator mediator, IOrderRepository orderRepository)
        {
            _mediator = mediator;
            _orderRepository = orderRepository;
        }

        public async Task OnGetAsync(Guid patientId)
        {
            // Get all data of a given patient:
            var query = new PatientDetailsQuery(patientId);
            var patientDetails = await _mediator.Send(query);

            if(patientDetails != null)
            {
                this.Patient = new PatientVM(patientDetails);
            }
        }

        // Method to support partial view updates of just Allergies:
        public async Task<PartialViewResult> OnGetAllergies(Guid patientId)
        {
            // Get just allergies:
            var query = new PatientDetailsQuery(patientId);
            var patientDetails = await _mediator.Send(query);

            return new PartialViewResult
            {
                ViewName = "AllergyList",
                ViewData = new ViewDataDictionary<List<string>>(ViewData, patientDetails?.Allergies)
            };
        }

        // Method to support partial view updates of just an order:
        public async Task<PartialViewResult> OnGetOrder(Guid patientId, Guid orderId)
        {
            var order = await _orderRepository.GetAsync(patientId, orderId);
            var orderVM = new OrderVM(order);
 
            return new PartialViewResult
            {
                ViewName = "Order",
                ViewData = new ViewDataDictionary<OrderVM>(ViewData, orderVM)
            };
        }
    }
}

src/nucoris.webapp/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace nucoris.webapp.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/nucoris.webapp/Pages/Search.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using nucoris.application.queries;
using nucoris.queries.PatientStateView;
using nucoris.webapp.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nucoris.webapp.Pages
{
    public class SearchModel : PageModel
    {
        private readonly MediatR.IMediator _mediator;

        public List<PatientVM> FoundPatients { get; set; }

        public SearchModel(MediatR.IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnPostAsync(string mrn, string givenName, string familyName)
        {
            // Note that if user specifies no search criteria we'll return all patients.

            var specification = new PatientStateViewSpecification(PatientAdmissionState.Any, mrn, givenName, familyName);
            var query = new PatientStateQuery(specification);
            var patients = await _mediator.Send(query);

            this.FoundPatients = patients.OrderBy(qp => qp.QueryPatient.UpperFamilyName).ThenBy(qp => qp.QueryPatient.UpperGivenName).
                Select(qp => new PatientVM(qp)).ToList();
        }
    }
}

src/nucoris.webapp/Pages/Admitted.cshtml
@page
@model nucoris.webapp.Pages.AdmittedModel
@{
    ViewData["Title"] = "Admitted Patients";
}

<h1 class="container nucoris-color mb-4">Admitted Patients</h1>

<partial name="PatientList" model="@Model.AdmittedPatients"/>

src/nucoris.webapp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container">
    <section title="Welcome" class="nucoris-border-left">
        <div>
            <h2 class="nucoris-color">Welcome!</h2>
            <p>
                <span class="text-primary font-weight-bold">nucoris</span> is the exploratory prototype
                of a cloud-native <em>healthcare information system</em> (HIS)
                that I have developed and used as a learning platform during a sabbatical leave.
                It’s built with <a href="https://deviq.com/solid/">SOLID</a> principles and a domain-driven approach 
                in the <a href="https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html">Clean Architecture</a> style. 
                The application layer is organized 
                around the <abbr title="Command Query Responsibility Segregation">CQRS</abbr> pattern, 
                with events being used to support business rules and for interoperability.
            </p>
            <p>
                What you are seeing now is a <a href="https://www.learnrazorpages.com/">Razor Page</a> slightly styled with
                <a href="https://getbootstrap.com/">Bootstrap</a> and rendered by an
                <a href="https://dotnet.microsoft.com/apps/aspnet/web-apps">ASP.NET Core</a> web app hosted by
                <a href="https://azure.microsoft.com/en-us/services/app-service/">Azure App Service</a>.
                The applications exposes also a REST API that some pages use to post simple commands and do partial view updates.
            </p>
            <p>
                In the backend, data is stored in
                <a href="https://azure.microsoft.com/en-us/services/cosmos-db/">Azure Cosmos DB</a>
                document database. Events are published to an
                <a href="https://azure.microsoft.com/en-us/services/service-bus/">Azure Service Bus</a>,
                where they are consumed by <a href="https://azure.microsoft.com/en-us/services/functions/">Azure Functions</a>
                and <a href="https://azure.microsoft.com/en-us/services/logic-apps/">Logic Apps</a>
                for interoperability and customization.
            </p>
            <p>
                For business analysis, <a href="https://azure.microsoft.com/en-us/services/data-factory/">Azure Data Factory</a>
                periodically transfers data from <span class="text-primary font-weight-bold">nucoris</span> Cosmos DB into a data warehouse
                supported by an <a href="https://azure.microsoft.com/en-us/services/sql-database/">Azure SQL Database</a>.
            </p>
        </div>
    </section>

    <section title="Architecture" class="nucoris-border-left">
        <div>
            <h2 class="nucoris-color">Architecture</h2>
            <p>
                I've spent some time analyzing the qualities we expect from an <abbr title="Healthcare Information System">HIS</abbr>
                and how Azure services and some well-known architectural patterns could help us to achieve them.
                I have documented my reflections in <span class="text-primary font-weight-bold">nucoris</span>
                <a href="https://nucoris.blob.core.windows.net/docs/nucoris%20Architecture.pdf" target="_blank">architecture document</a>.
                <br />For a visual overview of the architecture you can have a look at its
                <a href="https://nucoris.blob.core.windows.net/docs/nucoris%20Architecture%20Diagram.pdf" target="_blank">diagram</a>.
            </p>
            <p>
                One of the main patterns in <span class="text-primary font-weight-bold">nucoris</span> is <abbr title="Command Query Responsibility Segregation">CQRS</abbr>,
                which I use as described in my 
                <a href="https://nucoris.blob.core.windows.net/docs/nucoris%20CQRS%20Implementation.pdf" target="_blank">CQRS implementation document</a>.
            </p>
            <p>
                If you are considering using a NoSQL document database in your project
                you may be interested to read about my experience in
                <span class="text-primary font-weight-bold">nucoris</span> 
                <a href="https://nucoris.blob.core.windows.net/docs/nucoris%20Persistence.pdf" target="_blank">persistence document</a>.
            </p>
        </div>
    </section>

    <section title="Functionality" class="nucoris-border-left">
        <div>
            <h2 class="nucoris-color">Functionality</h2>
            <p>
                <span class="text-primary font-weight-bold">nucoris</span> is a prototype focused on exploring Azure backend technologies.
                It is not a final application and its user interface is very simple.
            </p>
            <p>
                You can see the list of patients currently admitted into the system (<a asp-page="/Admitted">Admitted</a> page) and
                from there jump into the details of a limited patient's health record. In the <em>Patient Details</em> page you can add/remove allergies
                and add, assign and stop medication orders. You can also inspect an audit trail of all events affecting the patient.
            </p>
            <p>
                If you wish so, you can admit a new patient from the <a asp-page="/NewAdmission">New Admission</a> page.
                If you prescribe a new medication order and assign it to you ("USER, Guest"),
                it will be listed in the <a asp-page="MyOrders">My Orders</a> page a few seconds later
                (it is maintained by an asynchronous process that relies on <em>Cosmos Change Feed</em> and <em>Azure Service Bus</em>).
            </p>
        </div>
    </section>

</div>

src/nucoris.webapp/Pages/MyOrders.cshtml
@page
@model nucoris.webapp.Pages.MyOrdersModel
@{
    ViewData["Title"] = "My Orders";
}

<h1 class="container nucoris-color">Orders Assigned to Me</h1>

<section class="container mt-4">
    <p class="alert alert-warning"><em>Note</em>: this page is only used to show that 
    the list of orders gets updated when you assign an order to your user.<br />
    It has no functionality by itself.</p>
    @foreach (var patient in Model.OrdersAssignedToMe)
    {
        <div class="card border-primary rounded-lg mb-3">
            <div class="card-body pb-3 pt-3">
                <h5 class="card-title">@patient.DisplayName</h5>
                <h6 class="card-subtitle">@patient.Mrn</h6>

                <div class="border-left border-primary mt-3 pl-3">
                    @foreach (var order in patient.ActiveAdmission.Orders)
                    {
                        <div class="text-truncate font-weight-bold">@order.Description</div>
                    }
                </div>
            </div>
        </div>
    }
</section>

src/nucoris.webapp/Pages/NewAdmission.cshtml
@page
@model nucoris.webapp.Pages.NewAdmissionModel
@{
    ViewData["Title"] = "New Admission";
}

<h1 class="container nucoris-color">New Admission</h1>

<section id="searchSection" class="container mt-4">
    <p class="alert alert-info">Please enter patient's medical record number (MRN):</p>
    <form asp-page="NewAdmission" asp-page-handler="Search" method="post">
        <div class="control-group form-group">
            <div class="controls">
                <label for="mrn">MRN:</label>
                <input name="mrn" type="text" class="form-control">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</section>


@* Note that the model defines a list of patients to be able to reuse the partial view "PatientList"
    but we know it will include at most one patient *@

@if (Model.FoundPatients != null && Model.FoundPatients.Any())
{
<section id="patientFoundSection" class="container">
    <div class="container nucoris-background mt-5 mb-1 d-sm-block" style="height: 2px">&nbsp;</div>

    @if (Model.FoundPatients[0].ActiveAdmission != null)
    {
        <p class="alert alert-warning">Patient is already admitted.</p>
    }

    <partial name="PatientList" model="@Model.FoundPatients" />

    @if (Model.FoundPatients[0].ActiveAdmission == null)
    {
        <form asp-page="NewAdmission" asp-page-handler="Admit" method="post">
            <div class="text-right mt-3">
                <input name="patientId" type="hidden" value="@Model.FoundPatients[0].Id" />
                <input type="submit" class="btn btn-success" value="Admit" />
            </div>
        </form>
    }
</section>
}
else if (Model.NewPatient != null && !String.IsNullOrWhiteSpace(Model.NewPatient.Mrn))
{
<section id="patientNotFoundSection" class="container">
    <div class="container nucoris-background mt-5 mb-1 d-sm-block" style="height: 2px">&nbsp;</div>

    <p class="alert alert-warning">Please complete patient's given name, family name and date of birth if known</p>
    <form asp-page="NewAdmission" asp-page-handler="NewPatient" method="post">
        <div class="form-group row">
            <label asp-for="NewPatient.Mrn" class="col-sm-3 col-lg-2 col-form-label">MRN:</label>
            <div class="col-sm-9 col-lg-10">
                <input asp-for="NewPatient.Mrn" class="form-control">
                <span asp-validation-for="NewPatient.Mrn" class="alert-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NewPatient.GivenName" class="col-sm-3 col-lg-2 col-form-label">Given name:</label>
            <div class="col-sm-9 col-lg-10">
                <input asp-for="NewPatient.GivenName" class="form-control">
                <span asp-validation-for="NewPatient.GivenName" class="alert-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NewPatient.FamilyName" class="col-sm-3 col-lg-2 col-form-label">Family name:</label>
            <div class="col-sm-9 col-lg-10">
                <input asp-for="NewPatient.FamilyName" class="form-control">
                <span asp-validation-for="NewPatient.FamilyName" class="alert-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NewPatient.DateOfBirth" class="col-sm-3 col-lg-2 col-form-label">Date of Birth:</label>
            <div class="col-sm-4">
                <input asp-for="NewPatient.DateOfBirth" class="form-control">
                <span asp-validation-for="NewPatient.DateOfBirth" class="alert-danger"></span>
            </div>
        </div>
        <div class="text-right">
            <button type="submit" class="btn btn-success">Save and Admit</button>
        </div>
    </form>
</section>

}

src/nucoris.webapp/Pages/NewOrder.cshtml
@page
@model nucoris.webapp.Pages.NewOrderModel
@{
    ViewData["Title"] = "Add New Order";
}

<h1 class="container nucoris-color">Add New Order</h1>
<h4 class="container my-3">@Model.Patient.DisplayName</h4>

<section class="container">
    <p class="alert alert-info my-2">Please enter the new order:</p>
    <form method="post">
        <input class="text-hide" asp-for="@Model.NewOrder.PatientId" />
        <input class="text-hide" asp-for="@Model.NewOrder.AdmissionId" />

        <div class="form-group row">
            <label asp-for="@Model.NewOrder.MedicationId" class="col-sm-5 col-lg-3 col-form-label">Medication:</label>
            <div class="col-sm-7 col-lg-9">
                <select asp-for="@Model.NewOrder.MedicationId" asp-items="@Model.MedicationForms" class="form-control"></select>
                <span asp-validation-for="@Model.NewOrder.MedicationId" class="alert-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="@Model.NewOrder.MedicationId" class="col-sm-5 col-lg-3 col-form-label">Administration Frequency:</label>
            <div class="col-sm-7 col-lg-9">
                <select asp-for="@Model.NewOrder.FrequencyId" asp-items="@Model.AdministrationFrequencies" class="form-control"></select>
                <span asp-validation-for="@Model.NewOrder.FrequencyId" class="alert-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="@Model.NewOrder.StartTime" class="col-sm-5 col-lg-3 col-form-label">Start Time:</label>
            <div class="col-sm-5">
                <input asp-for="@Model.NewOrder.StartTime" class="form-control" />
                <span asp-validation-for="@Model.NewOrder.StartTime" class="alert-danger"></span>
            </div>
        </div>
        <div class="text-right">
            <button type="submit" class="btn btn-success">Save and Close</button>
        </div>
    </form>
</section>

src/nucoris.webapp/Pages/PatientAuditTrail.cshtml
@page
@model nucoris.webapp.Pages.PatientAuditTrailModel
@{
    ViewData["Title"] = "Patient Audit Trail";
}

<h1 class="container nucoris-color">Patient Audit Trail</h1>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">@Model.PatientAuditTrail.DisplayName</h4>
        <h5 class="card-subtitle">@Model.PatientAuditTrail.Mrn</h5>
    </div>
</div>

<div class="container mt-3">
    @* Show header in all sizes except xs and sm *@
    <div class="row my-2 d-none d-md-flex px-0">
        <div class="col-md-3 col-lg-3 nucoris-background text-white rounded-left">User</div>
        <div class="col-md-4 col-lg-3 nucoris-background text-white">Time</div>
        <div class="col-md-5 col-lg-6 nucoris-background text-white rounded-right">Action</div>
    </div>
    @foreach (var item in Model.PatientAuditTrail.Items)
    {
        @* Show all properties in a single row except in xs and sm sizes.
            In xs/sm show properties one below the other,
            and draw a line between patients *@
    <div class="row">
        <div class="col-md-3 col-lg-3 text-truncate">@item.DoneBy</div>
        <div class="col-md-4 col-lg-3 text-truncate">@item.DoneAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss")</div>
        <div class="col-md-5 col-lg-6 text-truncate">@item.Description</div>
    </div>
        <div class="nucoris-background mb-3 d-md-none" style="height: 1px">&nbsp;</div>
    }

</div>